import numpy as np

#Task1
Vector1 = np.array([1, 2, -3,4])
Vector2 = np.array([2, 5, -3,2])
Vector3 = np.array([1, 4, 2, 2])
Vector4 = np.array([3, 5, 2, 3])
Vector5 = np.array([4, 1, 2, 4])
Vector6 = np.array([5, 2, 1, 5])
print('Vector1 =',np.linalg.norm(Vector1))
print('Vector2 =',np.linalg.norm(Vector2))
print('Vector3 =',np.linalg.norm(Vector3))
print('Vector4 =',np.linalg.norm(Vector4))
print('Vector5 =',np.linalg.norm(Vector5))
print('Vector6 =',np.linalg.norm(Vector6))
print('#'*100)
#Task2
VectorA = np.array([1,2,5,7,9])
VectorB = np.array([1,3,10,3,2])
VectorC = np.array([1,8,3,0,9 ])
VectorD = np.array([2,3,10,3,8])
VectorE = np.array([4,8,5,1,9])
VectorF = np.array([8,9,5,2,1])
print('(VectorA*VectorB) = ', np.inner(VectorA, VectorB))
print('(VectorC*VectorD) = ', np.inner(VectorC, VectorD))
print('(VectorE*VectorF) = ', np.inner(VectorE, VectorF))
print('#'*100)
#task3
a = np.array([-0.4, 4.3, -0.6])
b = np.array([-0.2, 0.2,  1.0])
c = np.array([-0.2, 2.1, -1.5])
#print(((np.square(a) + np.square(b) + np.square(c))))
#print(np.divide(np.multiply(a,(np.add(b, (np.multiply(a,b))))),c))
#print(np.linalg.norm(a+b+c))
print('(A**2 + B**2 + C**2)*(A*(B+A*B)/C)*||A + B + C||=',((np.square(a) + np.square(b) + np.square(c)) * (np.divide(np.multiply(a,(np.add(b, (np.multiply(a,b))))),c)))
*(np.linalg.norm(a+b+c)))
